### ISSUE TITLE
Points Config

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/EpicWarning#3]
```
UUID:
  banned: 'true'
  bannedreason: 'LOLOL'
  bannedby: 'JustBru00'
  tempbanned: 'false'
  tempbanuntil: '112631284'
  tempbanreason: 'LOLOLOLOL'
  tempbannedby: 'JustBru00'
  lastname: 'JustBru00'
  log:
    - 'JustBru00 kicked by JustBru00 for spam.' 
```
